### ISSUE TITLE
 `CXXABI_1.3.8' &  `GLIBCXX_3.4.20'  not found

### ISSUE THREAD

**Issue by frankstein-1** [openclonk/openclonk#8]
Hi 
I'm interested by your project. So, I download the Linux version (x64)
After installing the all dependencies . I got this message when I tried to run the game 
```bash
./openclonk: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./openclonk)
./openclonk: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./openclonk)
```
I think it's related to compiler version.  
```bash
 $ gcc --version 
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
But I have gcc-4.9-base 
what do you think ?

**Comment by SvenTwo** [comment]
Looks like some version mismatch. Try:

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`

to see which libs are in there. Also `ll /usr/lib/x86_64-linux-gnu/libstdc++.so.6` to check if this is maybe symlinked to an older version.

If all fails, you can clone from source and compile yourself (`cmake . && make all`). That should link against the GCC you have installed. There's also an old version of openclonk in the ubuntu repositories (`sudo apt-get install openclonk`), but it is outdated and has been greatly improved since then.

**Comment by isilkor** [comment]
Unfortunately it's infeasible to provide Linux binaries that work on every distribution in the wild (even big companies like Valve only officially support one)<sup>[1](#fn1)</sup>, so **we're only building snapshots for Debian Stable** (currently Jessie). However, for open source software that's not a problem because package management on pretty much every distribution is easy enough that it's no big deal to set up your own build environment -- we're trying to make sure that even if our binaries don't run out of the box, at least you shouldn't have too many issues compiling your own.
- - -
<sup><a name="fn1">1</a></sup> We could build statically linked binaries, but our build system (CMake) makes doing that without manually picking all required libraries a chore, and part of the reason we're doing automated linux builds in the first place is to make sure that building works without requiring any additional configuration.

**Comment by frankstein-1** [comment]
I use actually mint 17.1 rebbeca, the problem was in the compiler.
```bash
~/openclonk-6.1-src $ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
I downloaded the source and now it works.

**Comment by SynedraAcus** [comment]
Also mint17. Neiher [cmake 3+](https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04) nor [gcc-4.9](https://stackoverflow.com/questions/33458208/install-g-4-9-on-mint-17-2/33481438) are available from default repos. See the links for necessary repos, `apt-get update`, `apt-get upgrade` (cmake is kept back by default). Then you just:

$ CC=gcc-4.9 GXX=g++-4.9 cmake
$ make all

Guess it's trivial for c/c++-savvy folks, but maybe this post will save some googling for others like me.
